nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ['*']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    expose_headers: []
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['http://localhost:4200']
      allow_methods: ['POST', 'OPTIONS']
      allow_headers: ['Content-Type', 'Authorization']
      max_age: 3600
